In [6]:
import numpy as np
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(x[x>5])

[6 7 8 9]


In [8]:
x[x>5] = -1
print(x)

[[ 1  2  3]
 [ 4  5 -1]
 [-1 -1 -1]]


In [9]:
print(x)

[[ 1  2  3]
 [ 4  5 -1]
 [-1 -1 -1]]


In [10]:
print(np.sort(x))

[[ 1  2  3]
 [-1  4  5]
 [-1 -1 -1]]


In [11]:
print(x)

[[ 1  2  3]
 [ 4  5 -1]
 [-1 -1 -1]]


In [ ]:
x = np.range(1,10).reshape(3,3)