In [1]:
import numpy as np

x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [2]:
y = np.arange(11,20)
print(y)

[11 12 13 14 15 16 17 18 19]


In [3]:
print(x+y)

[12 14 16 18 20 22 24 26 28]


In [4]:
print(np.add(x,y))

[12 14 16 18 20 22 24 26 28]


In [5]:
print(x-y)
print(x/y)


[-10 -10 -10 -10 -10 -10 -10 -10 -10]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421]


In [6]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,10).reshape(3,3)
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(x+y)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
print(np.add(x,y))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [9]:
print(x-y)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
X = np.arange(1,10)
print(np.power(X,2))

[ 1  4  9 16 25 36 49 64 81]


In [11]:
print(np.sqrt(X))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [12]:
print(X)

[1 2 3 4 5 6 7 8 9]


In [13]:
X.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(X)

[1 2 3 4 5 6 7 8 9]


In [15]:
X = X.reshape(3,3)

In [16]:
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(X+3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
print(np.sum(X,axis = 1))

[ 6 15 24]


In [21]:
x = np.array([1,2,3])
print(X+x)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [23]:
x = np.arange(1,5).reshape(2,2)
print(x)
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(x+y)
#could not broadcast 2X2 , 3x3

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 