In [2]:
import numpy as np

array = np.array([1,2,3,4])

In [3]:
print(array)

[1 2 3 4]


In [4]:
print(type(array))

<class 'numpy.ndarray'>


In [5]:
array.dtype


dtype('int32')

In [6]:
print(array.shape)

(4,)


In [7]:
print(array.size)

4


In [8]:
zero = np.zeros((2,3),dtype = int)
print(zero)

[[0 0 0]
 [0 0 0]]


In [9]:
zero.dtype

dtype('int32')

In [10]:
ones = np.ones((4,3),dtype = int)
ones.dtype

dtype('int32')

In [11]:
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
const = np.full((4,2),5)
print(const)

[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [13]:
diag = np.eye(5)
print(diag)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
diag = np.diag([1,2,4])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 4]]


In [15]:
arrays = np.arange(10)
print(arrays)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
x = np.arange(4,10)
print(x)

[4 5 6 7 8 9]


In [17]:
x = np.linspace(0,10,10,endpoint = False)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [19]:
x = np.random.normal(0,0.1,size=(10,10))
print(x)

[[-1.77993672e-01 -2.05568137e-02 -5.28455867e-02  3.26079804e-02
  -2.16953299e-01 -3.19803027e-03  6.91783768e-02  6.10054646e-02
   3.30783637e-02 -8.02282599e-02]
 [-4.91728670e-02  1.92553013e-01 -3.13280590e-02 -2.77189074e-02
  -1.40167632e-01 -4.49052386e-02  3.45210117e-02 -2.01003357e-01
   4.99419155e-02  9.09135054e-03]
 [ 1.90084728e-01  7.63396997e-02 -1.90149623e-01 -1.69794807e-01
  -1.35134516e-01  1.83805925e-01  9.40672015e-02  3.03205001e-01
  -8.24287034e-02 -5.22442128e-02]
 [-2.83079085e-02  1.31629049e-01  9.37363982e-02  2.00145619e-02
   2.38668485e-03  6.14022128e-02 -1.08523764e-01  8.15226932e-03
  -2.08252333e-01  1.25697459e-01]
 [-8.94641268e-02  1.26110310e-02  3.43298168e-02  1.20570067e-01
  -1.15043038e-02 -7.29872787e-02  2.02769428e-02 -8.21271447e-02
   6.15974420e-04  2.23180802e-02]
 [ 5.06049841e-03 -3.56351275e-02 -3.12066531e-02 -4.76884026e-03
   1.38724514e-01  6.95301560e-02  3.01909220e-02  5.20533631e-02
   2.55193482e-02 -1.77197082e-02