In [21]:
import numpy as np

x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [25]:
y = x[1:4,2:4]
print(y)

[[ 8  9]
 [13 14]
 [18 19]]


In [27]:
z = x[:,2]
print(z)

[ 3  8 13 18]


In [50]:
a = [1,2,3,4]
print(a)

[1, 2, 3, 4]


In [51]:
b = a 
print(b)

[1, 2, 3, 4]


In [52]:
b[2] = 10
print(a)
print(b)

[1, 2, 10, 4]
[1, 2, 10, 4]


In [53]:
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x

print(x is z)
print(z)

# returns True because z is the same object as x

print(x is y)

# returns False because x is not the same object as y, even if they have the same content

print(x == y)

# to demonstrate the difference betweeen "is" and "==": this comparison returns True because x is equal to y


True
['apple', 'banana']
False
True
